/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eva2_problems_NativeProblem */

#ifndef _Included_eva2_problems_NativeProblem
#define _Included_eva2_problems_NativeProblem
#ifdef __cplusplus
extern "C" {
#endif
#undef eva2_problems_NativeProblem_serialVersionUID
#define eva2_problems_NativeProblem_serialVersionUID -3904130243174390134LL
/*
 * Class:     eva2_problems_NativeProblem
 * Method:    evaluate
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_eva2_problems_NativeProblem_evaluate
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     eva2_problems_NativeProblem
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eva2_problems_NativeProblem_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
